# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-21 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(default='Enter Desription Here'),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default='Enter Is Your location', max_length=50),
        ),
    ]
